---
title: R语言：ggplot2基础绘图
author: ''
date: '2019-06-01'
slug: r语言-ggplot2基础绘图
categories:
  - r

tags: []
---
条形图的绘制
```{r}
# 我们拿到这样的数据
name <- c("多","中","少","中","少")
data <- data.frame(name) # 转化为数据框
library(ggplot2)
# 简单地画出一个图
ggplot(data,aes(x=name)) + geom_bar()
# 画点图代码如下
data1 <- data.frame(a=1:3,b=3:1)
ggplot(data1,aes(a,b)) + geom_point()
###下面几种作图方式等价
###方式1 
ggplot(data,aes(x=name)) + geom_bar()
###方式2
ggplot(data) + geom_bar(aes(x=name))
###方式3
p <- ggplot(data,aes(x=name)) 
p + geom_bar()


```
简单参数的调整
```{r}
p <-ggplot(data,aes(x=name))

p + geom_bar(col="red") # 调整柱子边框颜色为红色（注意这里col不是柱子颜色）

p + geom_bar(fill="red") # 调整柱子颜色为红色(fill才是柱子内部颜色)

p + geom_bar(width=0.5) # 调整柱子宽度,1时两个柱子挨在一起，0.5则宽度是1时的一半

```
纵坐标使用百分比表示
```{r}
library(dplyr) # ggplot2 包常常和dplyr包一起使用
data1 <- data.frame(table(name))
data2 <- data1 %>% mutate(f=Freq/sum(Freq))
ggplot(data2,aes(name,f)) + geom_bar(stat="identity") +
  scale_y_continuous(breaks=seq(0,0.4,len=5), labels=paste(seq(0,0.4,len=5)*100,"%"))


```
更改横纵轴坐标、标题等
```{r}
p1 <- ggplot(data,aes(x=name)) + geom_bar(width=0.7)
p1 + xlab("种类") + ylab("") + 
  ggtitle("运动情况")

```
在图中增加标注的文字
```{r}
p2 <- ggplot(data,aes(x=name)) + 
  geom_bar(width=0.7,fill=rgb(50,163,221,maxColorValue=255)) + 
  xlab("种类") + ylab("") + ggtitle("运动情况")

(p3 <- p2 + geom_text(stat="count",
   label=paste(table(name)/sum(table(name))*100,'%',sep=''),
   colour = "black", vjust=-0.5, size=4.7))
```
主题自定义
```{r}
mytheme <- theme_bw() + 
  theme(plot.title=element_text(size=rel(2),hjust=0.5),
        axis.title=element_text(size=rel(1.5)),
        axis.text=element_text(size=rel(1.5)),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        panel.border=element_rect(color="white"),
        axis.line=element_line(color="gray",size=1))

p3 + mytheme
```
保存图形
ggplot2包中有专门的保存函数ggsave
```{r}
ggsave("1.png", dpi=300) # 默认保存最近的作图
ggsave("1.png", dpi=300, plot=p3) # 自己指定保存的图片
```

